### ISSUE TITLE
chibinekoサイトが最新のchromeでエラーになります

### ISSUE THREAD

**Issue by ichimaru-daiki** [tabbyz/chibineko#13]
Chromeの最新版で`https://chibineko.jp/`を開いた所、下記のエラーになりました。

<img width="962" alt="ss 2018-11-28 18 16 45" src="https://user-images.githubusercontent.com/13192788/49141404-db232880-f339-11e8-8ae4-64a677203210.png">

どうやらシマンテック系のSSLがChromeで信頼されなくなっているようです。
http://www.atmarkit.co.jp/ait/articles/1712/01/news033.html

無償でDigiCertで再発行できるようですので、SSL証明書の再発行をお願い致します。
https://www.slogical.co.jp/ssl/docs/i201711_symantec_digicert_chrome/

**Comment by tabbyz** [comment]
連絡ありがとうございます。
これを機に無料のSSL証明書に切り替えました。

**Comment by ichimaru-daiki** [comment]
見れるようになりました、対応ありがとうございました。
