### ISSUE TITLE
テストケースの項目を折りたためるようにしてほしい

### ISSUE THREAD

**Issue by nhnmomonga** [tabbyz/chibineko#3]
bootstrapのcollapseなどのような形で、テストケースを折りたためるようにすることはできないでしょうか？
http://getbootstrap.com/javascript/#collapse

**Comment by tabbyz** [comment]
やはり項目数が多い場合は折りたためた方がよいですよね。
まだ着手していませんが近々対応予定です。

**Comment by nhnmomonga** [comment]
ありがとうございます！
宜しくお願い致します。

**Comment by tabbyz** [comment]
@ba41b0e6374304bb447a359a701fa1bdd1d3052d
実装完了しました（chibineko.jpにも反映済みです）
イメージ通りであればcloseしてください。

**Comment by nhnmomonga** [comment]
イメージ通りです！ありがとうございます！:blush:
