### ISSUE TITLE
Rubyのバージョン指定について

### ISSUE THREAD

**Issue by Arakaki** [tabbyz/chibineko#6]
現在、gemfileにてRubyのバージョンを2.3と固定していますが、これはマストでしょうか。
2.2系の環境で運用しようとした際に、少々不便に思いました。

**Comment by tabbyz** [comment]
いえ、動作確認はしていませんがマストではありません。
おそらく2.2系でも問題なく動くかと思います。

**Comment by Arakaki** [comment]
> おそらく2.2系でも問題なく動くかと思います。

ありがとうございます、問題なく動いています。

余談ですが、バージョン指定を緩和いただけたら、より利用しやすくなるかなぁと思いました。
2.3に固定している経緯を知らないのでハズしていたらすみません :bow:

**Comment by Arakaki** [comment]
ご回答ありがとうございました。クローズします。

**Comment by tabbyz** [comment]
すみません、返答遅くなりました。

> バージョン指定を緩和いただけたら、より利用しやすくなるかなぁと思いました。

現在2.3なのは、開発時に使用していたバージョンで固定しているだけなので、とくに大きな理由はありません。ですので、バージョン指定の緩和については賛成です。

ただバージョンを下げるにあたり全体的なテストは必要ですので、時期については要検討とさせてください。おそらく、今後のリリースのタイミングになるかと思います。

**Comment by Arakaki** [comment]
> ただバージョンを下げるにあたり全体的なテストは必要ですので、時期については要検討とさせてください。おそらく、今後のリリースのタイミングになるかと思います。

ありがとうございます :bow:
