### ISSUE TITLE
readme.mdの改善

### ISSUE THREAD

**Issue by Arakaki** [tabbyz/chibineko#7]
ローカルで稼働確認する際に、今のREADMEでは不足していると思われる内容を記載したいです。

単純に下記を明記するだけです。

``` bash
$ git clone git@github.com:tabbyz/chibineko.git
$ cd chibineko

# 下記を追記
$bundle install
$rake db:create
$rake db:migrate 

$rails s

# access http://localhost:3000
```

**Comment by Arakaki** [comment]
すみません、ハズしているようなのでクローズします。失礼しました。

**Comment by tabbyz** [comment]
すみません、返答が遅くなりました。。

記載して頂いた内容ですが、Developmentモードでの起動になるためローカルで使用するにしても適さないかなと思っています。

それよりはgemで提供するようにして、下記のようにコマンド実行するだけで環境構築できれば、より手軽でよいかと考えています。

```
$ gem install chibineko
$ chibineko start
```
